#!/usr/bin/env sh

echo "Gathering Useful Package Information"

if [ ! -e configure.ac ]
then
  echo "Can not find 'configure.ac'"
  exit 1
fi

tmp=`grep AC_INIT configure.ac | sed -e 's/AC_INIT(//' -e 's/) *$//' -e 's/\[//g' -e 's/]//g' -e 's/ *//g'`
PKGNAME=`echo $tmp | cut -d, -f1`
PKGVERSION=`echo $tmp | cut -d, -f2`
PKGRELEASE=1

PKGGROUP="Development/Tools"
PKGAUTHOR="patrickhead@gmail.com"

mkdir -p packages

echo "Creating Binary Packages"

make dist

if which checkinstall && which makepkg > /dev/null
then

  echo "Creating Slackware Package"

  checkinstall -S -y \
    --install=no \
    --pkgname=$PKGNAME \
    --pkgversion=$PKGVERSION \
    --pkgrelease=$PKGRELEASE \
    --pkggroup="$PKGGROUP" \
    --pkglicense='GPLv3+' \
    --maintainer="$PKGAUTHOR" \
    --strip=yes \
    --stripso=yes \
    --gzman=yes \
    --newslack \
    --pakdir=packages \
    --backup=no \
    --addso=yes
fi

if which checkinstall && which rpmbuild > /dev/null
then

  echo "Creating RPM Package"

  if ! [ -d $HOME/rpmbuild ]
  then
    mkdir -p "$HOME/rpmbuild/{RPMS/x86_64,RPMS/noarch,RPMS/i386,SOURCES,SPECS,BUILD,BUILDROOT,SRPMS,tmp}"
  fi

  source="$PKGNAME-$PKGVERSION.tar.gz"

  if ! [ -e $HOME/rpmbuild/$source ]
  then
    cp $source $HOME/rpmbuild/SOURCES
  fi

  checkinstall -R -y \
    --install=no \
    --pkgname=$PKGNAME \
    --pkgversion=$PKGVERSION \
    --pkgrelease=$PKGRELEASE \
    --pkggroup="$PKGGROUP" \
    --pkglicense='GPLv3+' \
    --maintainer="$PKGAUTHOR" \
    --strip=yes \
    --stripso=yes \
    --gzman=yes \
    --pakdir=packages \
    --backup=no \
    --addso=yes \
    --spec=misc/egg.spec
fi

if which checkinstall && which dpkg > /dev/null
then

  echo "Creating Debian Package"

  checkinstall -D -y \
    --install=no \
    --pkgname=$PKGNAME \
    --pkgversion=$PKGVERSION \
    --pkgrelease=$PKGRELEASE \
    --pkggroup="$PKGGROUP" \
    --pkglicense='GPLv3+' \
    --maintainer="$PKGAUTHOR" \
    --strip=yes \
    --stripso=yes \
    --gzman=yes \
    --pakdir=packages \
    --backup=no \
    --addso=yes 
fi
